In [11]:
#Imports required libraries.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
df= pd.read_csv("W:\Anil\Infotact Solutions\Project2 Files\Cloning\SaaS-E-Commerce-Cohort-Retention-CLTV-Analysis\Data\Raw\Ecommerce_Dataset.csv.xls")

In [13]:
#head() function is used to see first few rows of csv file.
df.head()

,order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country
0,ORD0000001,CUST000001,2023-05-24,Fashion,4,144.98,579.92,2023-04-13,Instagram,Canada
1,ORD0000002,CUST000002,2024-03-18,Beauty,3,28.21,84.63,2024-03-11,Email,USA
2,ORD0000003,CUST000002,2024-04-09,Beauty,4,24.68,98.72,2024-03-11,Email,USA
3,ORD0000004,CUST000002,2024-05-05,Fashion,2,35.77,71.54,2024-03-11,Email,USA
4,ORD0000005,CUST000002,2024-06-20,Sports,2,19.67,39.34,2024-03-11,Email,USA

In [14]:
#Similar to head() , but retreives a random sample of rows for examining. 
df.sample(5)

,order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country
15770,ORD0015771,CUST004350,2023-12-15,Beauty,2,65.56,131.12,2023-09-23,Facebook Ads,France
52018,ORD0052019,CUST014381,2024-04-09,Books,3,132.57,397.71,2024-02-11,Direct,Australia
49514,ORD0049515,CUST013670,2024-04-04,Fashion,4,180.70,722.80,2024-01-01,Google Ads,France
40147,ORD0040148,CUST011118,2024-04-06,Electronics,3,64.47,193.41,2023-11-13,Email,Canada
66903,ORD0066904,CUST018638,2023-11-22,Home,3,61.77,185.31,2023-09-11,Google Ads,UK

In [15]:
df.shape

(71772, 10)

In [16]:
df.columns

Index(['order_id', 'customer_id', 'transaction_date', 'product_category',
       'quantity', 'unit_price', 'revenue', 'signup_date',
       'acquisition_channel', 'country'],
      dtype='str')

In [17]:
df.dtypes

order_id                   str
customer_id                str
transaction_date           str
product_category           str
quantity                 int64
unit_price             float64
revenue                float64
signup_date                str
acquisition_channel        str
country                    str
dtype: object

In [18]:
#Using info() function helps understand data
#Can verify Columns, total columns, Non-Null Columns, Datatypes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71772 entries, 0 to 71771
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             71772 non-null  str
 1   customer_id          71772 non-null  str
 2   transaction_date     71772 non-null  str
 3   product_category     71772 non-null  str
 4   quantity             71772 non-null  int64
 5   unit_price           71772 non-null  float64
 6   revenue              71772 non-null  float64
 7   signup_date          71772 non-null  str
 8   acquisition_channel  71772 non-null  str
 9   country              71772 non-null  str
dtypes: float64(2), int64(1), str(7)
memory usage: 5.5 MB

In [19]:
#Describe() functions gives a statistical Summary of the dataframe.
df.describe()

           quantity    unit_price       revenue
count  71772.000000  71772.000000  71772.000000
mean       2.500543    129.780982    324.114706
std        1.118278     69.358783    238.430900
min        1.000000     10.000000     10.000000
25%        2.000000     69.357500    134.310000
50%        2.000000    129.580000    248.285000
75%        4.000000    189.610000    469.920000
max        4.000000    249.990000    999.960000

In [20]:
#Converting Conversion_date column from str datatype to datetime dataype.
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

#Normalizing datetime format.Converts time in datetime to zeros.
#Handles data efficiently while working with Power BI.
df['transaction_date'] = df['transaction_date'].dt.normalize()

In [21]:
#Converting Conversion_date column from str datatype to datetime dataype.
df['signup_date'] = pd.to_datetime(df['signup_date'])

#Normalizing datetime format.Converts time in datetime to zeros.
#Handles data efficiently while working with Power BI.
df['signup_date'] = df['signup_date'].dt.normalize()

In [22]:
#Using info() function helps understand data
#Can verify Columns, total columns, Non-Null Columns, Datatypes
#Using this particular line to check if the datatype is changed from str to datetime
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71772 entries, 0 to 71771
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             71772 non-null  str
 1   customer_id          71772 non-null  str
 2   transaction_date     71772 non-null  datetime64[us]
 3   product_category     71772 non-null  str
 4   quantity             71772 non-null  int64
 5   unit_price           71772 non-null  float64
 6   revenue              71772 non-null  float64
 7   signup_date          71772 non-null  datetime64[us]
 8   acquisition_channel  71772 non-null  str
 9   country              71772 non-null  str
dtypes: datetime64[us](2), float64(2), int64(1), str(5)
memory usage: 5.5 MB

In [23]:
#Checking Duplicates.
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [31]:
df.isnull().sum()

order_id               0
customer_id            0
transaction_date       0
product_category       0
quantity               0
unit_price             0
revenue                0
signup_date            0
acquisition_channel    0
country                0
dtype: int64

In [41]:
df["Cohortmonth"]=(df.groupby("customer_id")["transaction_date"].transform("min"))
print(df["Cohortmonth"])

0       2023-05-24
1       2024-03-18
2       2024-03-18
3       2024-03-18
4       2024-03-18
           ...
71767   2024-05-19
71768   2024-05-19
71769   2024-05-19
71770   2023-03-30
71771   2023-06-08
Name: Cohortmonth, Length: 71772, dtype: datetime64[us]

In [24]:
df.to_csv('W:/Anil/Infotact Solutions/Project2 Files/Cloning/SaaS-E-Commerce-Cohort-Retention-CLTV-Analysis/Data/Cleaned/Cleaned_Ecommerce.csv' , index=False)