In [1]:
import pandas as pd
print(pd.__version__)

2.3.3

In [4]:
import sys
print(sys.executable)

c:\ProgramData\anaconda3\python.exe

In [5]:
import importlib.util

spec = importlib.util.find_spec("pandas")
print(spec.origin)

c:\ProgramData\anaconda3\Lib\site-packages\pandas\__init__.py

In [ ]:
#import necessary libraries
import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime 
import warnings
from pathlib import Path

In [8]:
from pathlib import Path
import pandas as pd
def load_dataset(filename="Ecommerce_Dataset.csv"):
   
    # Project root (assuming notebook is in the notebooks folder)
    project_root = Path.cwd().parent
    file_path = project_root / "data" / "raw" / filename

    if not file_path.exists():
        raise FileNotFoundError(
            f"Dataset not found at:\n{file_path}\n"
            "Ensure the CSV file exists in the data/raw folder."
        )

    Ecommerce_data = pd.read_csv(file_path)
    print(f"Dataset loaded successfully!")
    print(f"Shape: {Ecommerce_data.shape}")

    return Ecommerce_data

In [9]:
Ecommerce_data = load_dataset()
Ecommerce_data.head()

Dataset loaded successfully!
Shape: (71772, 10)

,order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country
0,ORD0000001,CUST000001,2023-05-24,Fashion,4,144.98,579.92,2023-04-13,Instagram,Canada
1,ORD0000002,CUST000002,2024-03-18,Beauty,3,28.21,84.63,2024-03-11,Email,USA
2,ORD0000003,CUST000002,2024-04-09,Beauty,4,24.68,98.72,2024-03-11,Email,USA
3,ORD0000004,CUST000002,2024-05-05,Fashion,2,35.77,71.54,2024-03-11,Email,USA
4,ORD0000005,CUST000002,2024-06-20,Sports,2,19.67,39.34,2024-03-11,Email,USA

In [10]:
def explore_dataset(df, name):
   
    print("=" * 60)
    print(f"Dataset: {name}")
    print("=" * 60)

    # Shape
    print(f"\nShape: {df.shape[0]} rows × {df.shape[1]} columns")

    # Column names
    print("\nColumns:")
    print(df.columns.tolist())

    # Data types and missing values
    print("\nDataset Information:")
    print(df.info())

    # Missing values
    print("\nMissing Values:")
    print(df.isnull().sum())

    # Summary statistics
    print("\nSummary Statistics:")
    print(df.describe(include='all').T)

    # First five rows
    print("\nFirst Five Rows:")
    display(df.head())

In [11]:
explore_dataset(Ecommerce_data, "Ecommerce Data")

============================================================
Dataset: Ecommerce Data
============================================================

Shape: 71772 rows × 10 columns

Columns:
['order_id', 'customer_id', 'transaction_date', 'product_category', 'quantity', 'unit_price', 'revenue', 'signup_date', 'acquisition_channel', 'country']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71772 entries, 0 to 71771
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             71772 non-null  object
 1   customer_id          71772 non-null  object
 2   transaction_date     71772 non-null  object
 3   product_category     71772 non-null  object
 4   quantity             71772 non-null  int64
 5   unit_price           71772 non-null  float64
 6   revenue              71772 non-null  float64
 7   signup_date          71772 non-null  object
 8   acquisition_channel  71772 non-null  object
 9   country              71772 non-null  object
dtypes: float64(2), int64(1), object(7)
memory usage: 5.5+ MB
None

Missing Values:
order_id               0
customer_id            0
transaction_date       0
product_category       0
quantity               0
unit_price             0
revenue                0
signup_date            0
acquisition_channel    0
country                0
dtype: int64

Summary Statistics:
                       count unique         top   freq        mean        std  \
order_id               71772  71772  ORD0000001      1         NaN        NaN
customer_id            71772  19076  CUST013052     22         NaN        NaN
transaction_date       71772    723  2024-06-20    157         NaN        NaN
product_category       71772      6     Fashion  12098         NaN        NaN
quantity             71772.0    NaN         NaN    NaN    2.500543   1.118278
unit_price           71772.0    NaN         NaN    NaN  129.780982  69.358783
revenue              71772.0    NaN         NaN    NaN  324.114706   238.4309
signup_date            71772    720  2023-09-30    229         NaN        NaN
acquisition_channel    71772      7   Instagram  10682         NaN        NaN
country                71772      6   Australia  12369         NaN        NaN

                      min      25%      50%     75%     max
order_id              NaN      NaN      NaN     NaN     NaN
customer_id           NaN      NaN      NaN     NaN     NaN
transaction_date      NaN      NaN      NaN     NaN     NaN
product_category      NaN      NaN      NaN     NaN     NaN
quantity              1.0      2.0      2.0     4.0     4.0
unit_price           10.0  69.3575   129.58  189.61  249.99
revenue              10.0   134.31  248.285  469.92  999.96
signup_date           NaN      NaN      NaN     NaN     NaN
acquisition_channel   NaN      NaN      NaN     NaN     NaN
country               NaN      NaN      NaN     NaN     NaN

First Five Rows:

,order_id,customer_id,transaction_date,product_category,quantity,unit_price,revenue,signup_date,acquisition_channel,country
0,ORD0000001,CUST000001,2023-05-24,Fashion,4,144.98,579.92,2023-04-13,Instagram,Canada
1,ORD0000002,CUST000002,2024-03-18,Beauty,3,28.21,84.63,2024-03-11,Email,USA
2,ORD0000003,CUST000002,2024-04-09,Beauty,4,24.68,98.72,2024-03-11,Email,USA
3,ORD0000004,CUST000002,2024-05-05,Fashion,2,35.77,71.54,2024-03-11,Email,USA
4,ORD0000005,CUST000002,2024-06-20,Sports,2,19.67,39.34,2024-03-11,Email,USA

In [12]:
print(Ecommerce_data.dtypes)

order_id                object
customer_id             object
transaction_date        object
product_category        object
quantity                 int64
unit_price             float64
revenue                float64
signup_date             object
acquisition_channel     object
country                 object
dtype: object